### ISSUE TITLE
Simple Example

### ISSUE THREAD

**Issue by meherett** [dbrainio/Soltsice#13]
Hey there, please tell me how can i use it?

"pragma solidity ^0.4.8;
contract Storage {
  uint256 storedData;
function set(uint256 data) public {
    storedData = data;
  }
function get() public constant returns (uint256) {
    return storedData;
  }
}"

**Comment by buybackoff** [comment]
There is a test for it: https://github.com/dbrainio/Soltsice/blob/master/src/tests/storage.test_.ts

First, you need to create a contract for your storage by calling a method on StorageFactory. The `getStorage` function does it for you. On mainnet `getStorage` requires additional true parameter because it will create a rather expensive transaction to create a new storage contract for you. Then you could read and write any solidity type as shown below.

The storage factory is already deployed on Mainnet, Ropsten and Rinkeby. 


```
it('Storage: Could get storage for account', async () => {
    let store = await getStorage(w3, activeAccount);
    // console.log('STORAGE: ', storage);
    let key = W3.EthUtils.bufferToHex(W3.EthUtils.sha3('record'));
    console.log('KEY: ', key);
    let tx = await store.setStringValue(key, 'record value', sendParams);
    console.log('TX: ', tx);
    let stored = await store.getStringValue(key, sendParams);
    console.log('STORED: ', stored);
    expect(stored).toBe('record value');
});
```
