### ISSUE TITLE
w3.eth.defaultAccount is undefined

### ISSUE THREAD

**Issue by bjornharvold** [dbrainio/Soltsice#21]
When I call w3.eth.defaultAccount with MetaMask connected I am still getting undefined.

When I make a call to a function on my contract, I get an invalid address. I am assuming the defaultAccount does not get set by MetaMask at the time the function call is executed.

Now there could potentially be a lot of different reasons for this happening that I am not privy to. I would assume it would not be necessary to set the defaultAccount on the contract manually if I am using MetaMask. Could it be that Soltsice is the problem?

Please help

**Comment by buybackoff** [comment]
We can't do anything with the `web3` returning an undefined value. However, if you provide a default account to `W3` ctor, we will set that value to `w3.web3.eth.defaultAccount`. However, we will now remove `w3.eth` getter, you will have to use `w3.web3.eth` to get untyped `web3` members.

`w3` instance also has `isPre1API` and `web3API` properties so that you could detect which version of web3 Soltsice uses. Currently we use 0.20.x, but we try to hide the explicit `web3` API and provide the most important `web3` methods that are version-independent.
